#!/usr/bin/env bash
set -e

# TODO: has UI?

UBUNTU_RELEASE=`lsb_release -c -s`
HOME_DIR="/home/`whoami`"
DOT_DIR="$HOME_DIR/.dotfiles/"
CURRENT_DIR=`pwd`

if [ ! -f ~/.ssh/id_rsa ]; then
  echo "[i] Specify a password for the ssh key"
  ssh-keygen -t rsa -b 4096 -C `whoami`@`hostname` -f ~/.ssh/id_rsa
fi

echo "[i] Ask for sudo password"
sudo -v

sudo apt update
sudo apt dist-upgrade -y
sudo apt upgrade -y
# Stuff needed for other parts
sudo apt-get install -y apt-transport-https ca-certificates gnupg software-properties-common wget gnupg-agent
sudo apt install -y build-essential curl git zsh python3-dev python3-pip

# Console stuff used often by me
sudo apt install -y mc vim tig silversearcher-ag clang clang-format libc++-dev libc++abi-dev tmux ssh lldb ninja-build build-essential cmake pcp pipenv

# Build latest cmake release
if [ ! -d "$DOT_DIR/cmake_src" ]; then
  git clone https://gitlab.kitware.com/cmake/cmake.git "$DOT_DIR/cmake_src"
fi
cd "$DOT_DIR/cmake_src"
git clean -xdf
git reset --hard HEAD
git checkout release
git pull

if [ ! -d "$DOT_DIR/cmake_build" ]; then
  mkdir -p "$DOT_DIR/cmake_build"
  cd  "$DOT_DIR/cmake_build"
  CC=clang CXX=clang++ cmake -GNinja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX="$HOME_DIR/.local/" "../cmake_src"
fi
cd  "$DOT_DIR/cmake_build"
ninja install

cd "$CURRENT_DIR"
 

# DOCKER
if [ ! -x docker ]; then
	curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
	sudo add-apt-repository \
		 "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
		 $(lsb_release -cs) \
		 stable"
  sudo apt-get update
fi
sudo apt-get install -y docker-ce docker-ce-cli containerd.io
sudo usermod -aG docker `whoami`

# MBT

# Generating a unique ssh key

# Generating peer vpn keys?

# UI Stuff used often by me
sudo apt install -y rxvt-unicode i3 rofi keepassx j4-dmenu-desktop
# CHROME
if [ ! -f /etc/apt/sources.list.d/google-chrome.list ]; then
  wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
  sudo apt-get update
  sudo apt-get install -y google-chrome-stable
fi


# Even more limited stuff:
# openvpn
#if [ ! -x openvpn ]; then
#  wget -O - https://swupdate.openvpn.net/repos/repo-public.gpg|sudo apt-key add -
#  sudo sh -c 'echo "deb http://build.openvpn.net/debian/openvpn/stable `lsb_release -sc` main" > /etc/apt/sources.list.d/openvpn-aptrepo.list'
#  sudo apt-get update
#fi
sudo apt-get install -y openvpn
# Dropbox
sudo apt install -y nautilus-dropbox
# Slack
sudo snap install slack --classic
# Zoom
# XChat

# PowerLine setup
git clone https://github.com/powerline/fonts.git --depth=1
cd fonts
./install.sh
cd ..
rm -rf fonts

# Modify default shell to zsh
sudo usermod -s /usr/bin/zsh `whoami`

./install
