---
- name: Add Packman repository
  community.general.zypper_repository:
    name: packman
    repo: https://ftp.gwdg.de/pub/linux/misc/packman/suse/openSUSE_Tumbleweed/
    auto_import_keys: true
    autorefresh: true
    enabled: true
    priority: 90
  become: true

- name: Add NVIDIA repository
  community.general.zypper_repository:
    name: NVIDIA
    repo: https://download.nvidia.com/opensuse/tumbleweed
    auto_import_keys: true
    autorefresh: true
    enabled: true
    overwrite_multiple: true
  become: true
  when: desktop_nvidia_gpu

- name: Install NVIDIA driver packages
  ansible.builtin.command:
    cmd: zypper --non-interactive --gpg-auto-import-keys install --auto-agree-with-licenses nvidia-video-G06 nvidia-driver-G06-kmp-default nvidia-gl-G06
  become: true
  when: desktop_nvidia_gpu
  register: nvidia_install
  changed_when: "'Nothing to do' not in nvidia_install.stdout"

- name: Import NVIDIA Container Toolkit GPG key
  ansible.builtin.rpm_key:
    key: https://nvidia.github.io/libnvidia-container/gpgkey
    state: present
  become: true
  when: desktop_nvidia_gpu

- name: Add NVIDIA Container Toolkit repository
  community.general.zypper_repository:
    name: nvidia-container-toolkit
    repo: https://nvidia.github.io/libnvidia-container/stable/rpm/x86_64
    auto_import_keys: true
    autorefresh: true
    enabled: true
  become: true
  when: desktop_nvidia_gpu

- name: Install NVIDIA container toolkit
  ansible.builtin.package:
    name: nvidia-container-toolkit
    state: present
  become: true
  when: desktop_nvidia_gpu

- name: Generate NVIDIA CDI spec
  ansible.builtin.command:
    cmd: nvidia-ctk cdi generate --output /etc/cdi/nvidia.yaml
  become: true
  when: desktop_nvidia_gpu
  register: cdi_generate
  changed_when: cdi_generate.rc == 0
