# ddesk-specific Hyprland configuration
# Customize monitor layout, hardware-specific settings, etc.

# Monitor configuration
# Use `hyprctl monitors all` to list available monitors
# Format: monitor = name, resolution@rate, position, scale
# monitor = , preferred, auto, 1
$monitorLeft = HDMI-A-1
$monitorRight = DP-2

# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=$monitorRight,3840x2160,0x0,1.5
monitor=$monitorLeft,3840x2160,auto-left,1.5

workspace = 0,monitor:$monitorLeft
workspace = 1,monitor:$monitorLeft
workspace = 2,monitor:$monitorLeft
workspace = 3,monitor:$monitorLeft
workspace = 4,monitor:$monitorLeft
workspace = 5,monitor:$monitorLeft
workspace = 6,monitor:$monitorLeft
workspace = 7,monitor:$monitorLeft
workspace = 8,monitor:$monitorLeft
workspace = 9,monitor:$monitorLeft
workspace = 11,monitor:$monitorRight
workspace = 12,monitor:$monitorRight
workspace = 13,monitor:$monitorRight
workspace = 14,monitor:$monitorRight
workspace = 15,monitor:$monitorRight
workspace = 16,monitor:$monitorRight
workspace = 17,monitor:$monitorRight
workspace = 18,monitor:$monitorRight
workspace = 19,monitor:$monitorRight
workspace = 10,monitor:$monitorRight
